/*
 * This source file was generated by the Gradle 'init' task
 */
package com.reynolds.open_resume_platform;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LrTestLibTest {
    @Test void someLibraryMethodReturnsTrue() {
        assertNotNull(MockData.getCvMarkdown());
    }
}
