import { useState, useEffect } from 'react';
import { listTemplates, createTemplate } from '../api/templates.js';
import Button from '../components/Button.jsx';
import Card from '../components/Card.jsx';
import ErrorBanner from '../components/ErrorBanner.jsx';
import LoadingSkeleton from '../components/LoadingSkeleton.jsx';

export default function Templates() {
  const [templates, setTemplates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showAddModal, setShowAddModal] = useState(false);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState(null);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await listTemplates();
      setTemplates(data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const handleAdd = async (e) => {
    e.preventDefault();
    const trimmedName = name.trim();
    if (!trimmedName) return;
    setCreating(true);
    setCreateError(null);
    try {
      await createTemplate({ name: trimmedName, description: description.trim() || undefined });
      setShowAddModal(false);
      setName('');
      setDescription('');
      load();
    } catch (e) {
      setCreateError(e.message);
    } finally {
      setCreating(false);
    }
  };

  if (loading) {
    return (
      <div>
        <h1 className="text-xl sm:text-2xl font-semibold text-gray-800 mb-6">
          Templates
        </h1>
        <LoadingSkeleton />
      </div>
    );
  }

  if (error) {
    return (
      <div>
        <h1 className="text-xl sm:text-2xl font-semibold text-gray-800 mb-6">
          Templates
        </h1>
        <ErrorBanner
          message={error}
          action={<Button variant="danger" onClick={load}>Retry</Button>}
        />
      </div>
    );
  }

  return (
    <div>
      <div className="flex flex-wrap items-center justify-between gap-2 mb-6">
        <h1 className="text-xl sm:text-2xl font-semibold text-gray-800">Templates</h1>
        <Button variant="primary" onClick={() => setShowAddModal(true)}>
          Add template
        </Button>
      </div>
      {templates.length === 0 ? (
        <Card className="p-8 text-center">
          <p className="text-muted mb-4">No templates yet.</p>
          <Button variant="primary" onClick={() => setShowAddModal(true)}>
            Add your first template
          </Button>
        </Card>
      ) : (
        <div className="space-y-4">
          {templates.map((t) => (
            <Card key={t.id} className="p-5">
              <div className="font-semibold text-gray-900">{t.name}</div>
              <div className="text-muted text-sm mt-1">{t.description || '—'}</div>
              <div className="text-muted text-xs mt-1 font-mono">{t.id}</div>
            </Card>
          ))}
        </div>
      )}

      {showAddModal && (
        <div
          className="fixed inset-0 z-10 flex items-center justify-center bg-black/50 p-4"
          onClick={() => !creating && setShowAddModal(false)}
        >
          <div
            className="bg-surface rounded-lg shadow-xl max-w-md w-full p-6"
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="text-lg font-semibold text-gray-800 mb-3">Add template</h3>
            <p className="text-muted text-sm mb-4">
              Create a template with a name and optional description. The ID is generated by the server.
            </p>
            <form onSubmit={handleAdd}>
              {createError && (
                <div className="mb-3">
                  <ErrorBanner message={createError} compact />
                </div>
              )}
              <label htmlFor="template-name" className="block text-sm font-medium text-gray-700 mb-1">
                Name
              </label>
              <input
                id="template-name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full rounded border border-gray-300 px-3 py-2 text-gray-900 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary mb-4"
                placeholder="e.g. Banking – Conservative"
                required
              />
              <label htmlFor="template-desc" className="block text-sm font-medium text-gray-700 mb-1">
                Description (optional)
              </label>
              <input
                id="template-desc"
                type="text"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full rounded border border-gray-300 px-3 py-2 text-gray-900 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary mb-4"
                placeholder="e.g. Formal layout for banking roles"
              />
              <div className="flex gap-2 justify-end">
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() => {
                    setShowAddModal(false);
                    setCreateError(null);
                    setName('');
                    setDescription('');
                  }}
                  disabled={creating}
                >
                  Cancel
                </Button>
                <Button type="submit" variant="primary" disabled={creating || !name.trim()}>
                  {creating ? 'Creating…' : 'Create'}
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
